#!/usr/bin/python3
"""A module that contains the class defination of City """
from sqlalchemy import Column, Integer, String, ForeignKey
from model_state import Base


class City(Base):
    """
        Defining the schematics for the class City

        id (Integer): autogenerated unique value
        name(String): name of the city
        state_id(Integer): id for the state whrer the city is
    """

    __tablename__ = "cities"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(128), nullable=False)
    state_id = Column(Integer, ForeignKey('states.id'), nullable=False)
